version: '3.8'

services:
  neo4j-api-test-neo4j:
    image: neo4j:4.2@sha256:e1a8800a151094b049a231ff005bf1fae68af8f91a5661e5259f3d2a9413423c
    ports:
      - published: $NEO4J_TEST_NEO4J_HTTP_PORT
        target: 7474
      - published: $NEO4J_TEST_NEO4J_BOLT_PORT
        target: 7687
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
