version: '3.8'

services:
  neo4j:
    container_name: contents-api-test-neo4j
    image: neo4j:latest@sha256:732105228bb4baefe77361def4cd4709c31061abc98387bf9d09730447cd8ece
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
