version: '3.8'

services:
  neo4j:
    container_name: contents-api-test-neo4j
    image: neo4j:latest@sha256:7ac9387fd60c7fc2f2b983567dd838e181de40fb99c8c6aec6147b6699012dfb
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
